# Generated by Django 4.2.3 on 2023-07-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='issue_list',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_agent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_mech',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('INQUEUE', 'In Queue'), ('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('CLEARED', 'Cleared')], default='INQUEUE', max_length=20),
        ),
    ]
